server:
  port: '7000'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_URL}

spring:
  application:
    name: socket-streamer
  profiles:
    #active: local
    active: deploy
  redis:
    host: ${REDIS_URI}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'false'

#SECRET KEY
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
token:
  access-expired-time : 3600000
  refresh-expired-time : 3600000