#port
server:
  port: '7000'

spring:
  profiles:
    active: alpha
  freemarker:
    suffix: .ftl
    cache: 'false'
    template-loader-path: classpath:/templates
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'false'